Theme
t007rushi/Monkeep pull request #7
Opened 2022-03-31 05:15 UTC by t007rushi

2022-03-31 13:59 UTC, Manju-sree requested changes
UI looks cool with toggle, please try to add proper description, i have noticed that when in light mode, in (Take a Note..) section words are not visible.

2022-03-31 15:48 UTC, JantuDeb approved these changes
This is really awesome that you have used rich text editor.
You have some issues with UI like, lists numbers are overflowing the note card

2022-04-01 07:39 UTC, Manju-sree approved these changes
Good job !!, This PR is good to merge now.

2022-04-01 07:39 UTC, Manju-sree commented on src/context/theme-context.js
> +  useLayoutEffect(() => {
it's new to me about using useLayoutEffect( ).good to see you have implemented it. but not sure you have used javascript in this.

2022-04-01 07:39 UTC, Manju-sree commented on src/App.css
> +.dark-theme {
good to see clean code and you have put so much efforts in making dark and light theme.

2022-04-01 09:00 UTC, t007rushi commented on src/context/theme-context.js
> +  useLayoutEffect(() => {
No, its hook same as useEffect just sync

2022-04-01 09:01 UTC, merged